- Task: |
    Skonfiguruj autouzupełnianie dla `kubectl` w bieżącej sesji Bash-a, pakiet `bash-completion` jest już zainstalowany.
  Code: |
    source \
      &lt;(kubectl completion bash)
- Task: |
    Dodaj autouzupełnianie dla `kubectl` w Bash-u dla wszystkich sesji.
  Code: |
    echo \
      "source \
        &lt;(kubectl completion bash)" \
        >> ~/.bashrc
- Task: |
    Dodaj alias `k` dla polecenia `kubectl` tak, aby działało dla niego autouzupełnianie.
  Code: |
    alias k=kubectl
    complete \
      -o default \
      -F __start_kubectl \
        k
- Task: |
    Utwórz w Bashu alias `kx` który będzie ustawiał lub wyświetlał bieżący kontekst polecenia `kubectl`.
  Code: |
    alias kx='f() { \
      [ "$1" ] \
      && kubectl config \
        use-context $1 \
      || kubectl config \
        current-context; \
      }; \
      f'
- Task: |
    Utwórz w Bashu alias `kn` który będzie ustawiał lub wyświetlał przestrzeń nazw w bieżącym kontekście polecenia `kubectl`.
  Code: |
    alias kn='f() { \
      [ "$1" ] \
      && kubectl config \
        set-context \
          --current \
          --namespace $1 \
      || kubectl config \
        view \
          --minify \
      | grep namespace \
      | cut -d" " -f6 ; \
      }; \
      f'
