version: '3'

vars:
  GIT_BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  BUILD_DATE:
    sh: date '+%Y-%m-%d'
  ITEMS: |
  COMMENT: |
    out/arabic.apkg:dat/lang-vocabulary/arb/flashcard.yml
    out/chinese-simplified.apkg:dat/lang-vocabulary/cmn-hans/flashcard.yml
    out/chinese-traditional.apkg:dat/lang-vocabulary/cmn-hant/flashcard.yml
    out/czech.apkg:dat/lang-vocabulary/ces/flashcard.yml
    out/levantine-arabic.apkg:dat/lang-vocabulary/apc/flashcard.yml
    out/egyptian-arabic.apkg:dat/lang-vocabulary/arz/flashcard.yml
    out/farsi.apkg:dat/lang-vocabulary/fas/flashcard.yml
    out/french.apkg:dat/lang-vocabulary/fra/flashcard.yml
    out/german.apkg:dat/lang-vocabulary/deu/flashcard.yml
    out/hebrew.apkg:dat/lang-vocabulary/heb/flashcard.yml
    out/hungarian.apkg:dat/lang-vocabulary/hun/flashcard.yml
    out/spanish.apkg:dat/lang-vocabulary/spa/flashcard.yml
    out/turkish.apkg:dat/lang-vocabulary/tur/flashcard.yml
    out/vietnamese.apkg:dat/lang-vocabulary/vie/flashcard.yml

tasks:

  clean:
    desc: Delete generated files
    cmds:
      - rm -f {{ .TASKFILE_LOCATION }}/out/*.apkg

  build:
    desc: Build all packages
    silent: true
    cmds:
      - for:
          var: ITEMS
        task: build-package
        vars:
          ITEM: '{{ .ITEM }}'

  build-package:
    desc: Build package
    internal: true
    silent: true
    cmd: |
      IFS=: read -r outfile infile <<< {{ .ITEM }}
      echo "$(date '+%Y-%m-%d %H:%M:%S') ${outfile} ${infile}"
      uv run anki-build build ./${infile} -o ./${outfile}
    requires:
      vars:
        - ITEM
