name: Build vocabulary
description: Build Anki vocabulary apkg

inputs:
  input-project:
    description: Directory with input vocabulary
    required: true
  output-apkg:
    description: Directory to output vocabulary 
    required: true


runs:
  using: composite
  steps:

  - name: Build apkg
    shell: bash
    run: |
      outdir=$( dirname -- "${{ inputs.output-apkg }}" )
      mkdir -p "${outdir}"
      uv run anki-build build "${{ inputs.input-project }}" -o "${{ inputs.output-apkg }}"
