name: Build vocabulary
description: Build Anki vocabulary apkg

inputs:
  input-project:
    description: Directory with input vocabulary
    required: true
  output-apkg:
    description: Directory to output vocabulary 
    required: true


runs:
  using: composite
  steps:

  - name: Build apkg
    shell: bash
    run: |
      ls -la
      uv run anki-build build ${{ inputs.input-project }} -o ${{ inputs.output-apkg }}
