name: Release apkg
description: Create GitHub release with apkg files

inputs:
  version:
    description: Release version
    required: true
  apkg-folder:
    description: Directory with apkg files
    required: true

runs:
  using: composite
  steps:

  - name: Release APKG
    shell: bash
    env:
      GH_TOKEN: ${{ github.token }}
    run: |
      gh release create v${{ inputs.version }} ${{ inputs.apkg-folder }}/*.apkg
