name: build

on:
    workflow_dispatch:
        inputs:
            language:
                description: List of languages
                required: true

env:
    PYTHON_VERSION: 3.12
    UV_VERSION: latest

jobs:

    build:

        runs-on: [ubuntu-latest]

        steps:

        -   name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

        -   name: Make tools
            id: tools
            uses: ./.github/actions/make-tools

        -   name: Arabic (Syrian) vocabulary
            if: ${{ contains(inputs.language, 'apc') }}
            uses: ./.github/actions/build-vocabulary
            with:
                input-project: dat/lang-vocabulary/apc/flashcard.yml
                output-apkg: out/syrian-arabic.apkg

        -   name: Arabic (Standard) vocabulary
            if: ${{ contains(inputs.language, 'arb') }}
            uses: ./.github/actions/build-vocabulary
            with:
                input-project: dat/lang-vocabulary/arb/flashcard.yml
                output-apkg: out/arabic.apkg

        -   name: Arabic (Egyptian) vocabulary
            if: ${{ contains(inputs.language, 'arz') }}
            uses: ./.github/actions/build-vocabulary
            with:
                input-project: dat/lang-vocabulary/arz/flashcard.yml
                output-apkg: out/egyptian-arabic.apkg

        -   name: Make release
            id: release
            uses: ./.github/actions/make-release
